### ISSUE TITLE
Missing data in the raw RICO dataset

### ISSUE THREAD

**Issue by zhenglilei** [luileito/enrico#1]
Some screen_ids in the design_topics.csv are missing in the RICO dataset.

For example, 
not exist ../semantic_annotations/59905.json
not exist ../semantic_annotations/27800.json
not exist ../semantic_annotations/55842.json
not exist ../semantic_annotations/46677.json
not exist ../semantic_annotations/52477.json
not exist ../semantic_annotations/67925.json
not exist ../semantic_annotations/41081.json
not exist ../semantic_annotations/19141.json
not exist ../semantic_annotations/52489.json
not exist ../semantic_annotations/71388.json
not exist ../semantic_annotations/67933.json

**Comment by luileito** [comment]
Yes, we noticed that the original Rico dataset has been modified since its very first release. That's why in this repo we provide a series of associated files. Please see [Dataset files overview](https://github.com/luileito/enrico#dataset-files-overview) section in the README.

In your particular case, please download http://userinterfaces.aalto.fi/enrico/resources/hierarchies.zip

**Comment by zhenglilei** [comment]
Thanks a lot!
