### ISSUE TITLE
Issue in component_legend.json

### ISSUE THREAD

**Issue by Liangda-w** [luileito/enrico#3]
Hi, where can I find these components/text button/icon legend files in the Rico dataset?

I noticed in the component_legend.json the component `Icon` is missing, any reason behind this?
Also, I've tested the RGB color of some components and find some little deviation, e.g. `Background image` is (211, 20, 83) in the legend file, but (211, 12, 82) on the wireframe image. Is this deviation normal and can be ignored?

Thanks!

**Comment by luileito** [comment]
Hi, you can find the legend files in the root folder: they end with "*_legend.json". They were downloaded from https://interactionmining.org/rico and for some reason they are no longer available.

Regarding the RGB color values, there might be some differences because of your monitor's color calibration. Those RGB values were taken from the original Rico repository.

**Comment by Liangda-w** [comment]
Okay, thank you 😄
